### ISSUE TITLE
Can't build autaxx (no alphabeta/sorter.hpp)

### ISSUE THREAD

**Issue by jdermont** [kz04px/autaxx#1]
I'm trying to build using the instructions. I built libataxx succesfully, but I can't build autaxx. I get this error:

`autaxx/tests/alphabeta_sorter.cpp:6:10: fatal error: ../src/search/alphabeta/sorter.hpp: No such file
    6 | #include "../src/search/alphabeta/sorter.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/autaxx-test.dir/build.make:199: CMakeFiles/autaxx-test.dir/tests/alphabeta_sorter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/autaxx-test.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
`

Then I commented out tests/alphabeta_sorter.cpp to ignore the test, but I got this error:

`In file included from /home/jacek/ataxx/autaxx/src/options.cpp:1:
/home/jacek/ataxx/autaxx/src/options.hpp:55:32: error: ‘string’ in namespace ‘std’ does not name a type
   55 |     explicit String(const std::string &d) : default_(d) {
      |                                ^~~~~~
/home/jacek/ataxx/autaxx/src/options.hpp:6:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
    5 | #include <vector>
  +++ |+#include <string>
    6 | 
/home/jacek/ataxx/autaxx/src/options.hpp:58:25: error: ‘string’ in namespace ‘std’ does not name a type
   58 |     void set(const std::string &n) {
      |                         ^~~~~~
/home/jacek/ataxx/autaxx/src/options.hpp:58:20: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
   58 |     void set(const std::string &n) {
      |                    ^~~
/home/jacek/ataxx/autaxx/src/options.hpp:61:10: error: ‘string’ in namespace ‘std’ does not name a type
   61 |     std::string get() const {
......
`

I use Arch Linux.

**Comment by kz04px** [comment]
Thanks a lot for bringing this to my attention, it should now be fixed. The missing file was because I renamed the "alphabeta" search to "tryhard" at some point in time, but I never built the test executable to check that it still compiled.

Now that the test executable does compile, I realise one of the tests fails - thankfully that test is insignificant, but I will fix it shortly.

**Comment by kz04px** [comment]
> Now that the test executable does compile, I realise one of the tests fails - thankfully that test is insignificant, but I will fix it shortly.

A libataxx FEN parsing issue has been fixed in [this](https://github.com/kz04px/libataxx/commit/4dc8eed8b01ffea26e8e6a04110b1a99dcd22ca4) commit, and the libataxx version in Autaxx has been updated in [this](https://github.com/kz04px/autaxx/commit/46c540ec7159e2194f4b9a40370e7233f39e0953) commit. All Autaxx tests should now pass.

Please let me know if you have an other issues, questions, or comments in general. Thanks.
